-- V20260903142615__CREATE_TABLE_TGFAGE.sql generated via Maven Antrun

CREATE TABLE TGFAGE (
    CODAGE BIGINT IDENTITY(1,1) NOT NULL,
    INICIO DATETIME2 NOT NULL,
    FIM DATETIME2 NOT NULL,
    CODCLI BIGINT,
    DTINC DATETIME2 DEFAULT GETDATE(),
    DTALTER DATETIME2 DEFAULT GETDATE(),
    CONSTRAINT UK_TGFAGE_INTERVAL UNIQUE (INICIO, FIM),
    CONSTRAINT FK_TGFCLI_TGFAGE FOREIGN KEY (CODCLI)
        REFERENCES TGFCLI(CODCLI)
);