-- V20260903141536__CREATE_TABLE_TGFCLI.sql generated via Maven Antrun

CREATE TABLE TGFCLI (
    CODCLI BIGINT IDENTITY(1,1) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(20),
    DTINC DATETIME2 DEFAULT GETDATE(),
    DTALTER DATETIME2 DEFAULT GETDATE(),
    CONSTRAINT PK_TGFCLI PRIMARY KEY (CODCLI),
    CONSTRAINT UK_TGFCLI_EMAIL UNIQUE (EMAIL)
);
